Clean & refacto code Add lof if error during install/purge

diff --git a/ukupgrade b/ukupgrade
--- a/ukupgrade
+++ b/ukupgrade
@@ -44,16 +44,21 @@ function cleanTmp() {
 	sudo rm -rf /tmp/linux-*.deb
 }
 
+function error() {
+	cleanTmp
+	fatalError "$1";
+}
+
 function download() {
 	local filename=$(basename "$package");
 
-	if ! execCmd "wget -q -P /tmp $package"; then fatalError "Download of $package failed!"; fi
+	if ! execCmd "wget -q -P /tmp $package"; then error "Download of $package failed!"; fi
 
 	if [[ ! "${checksums[@]}" =~ "$(shasum /tmp/$filename | awk '{ print $1 }')" ]]; then
 		echo "Checksum failed for $filename !!!";
 
 		((trys++))
-		if [[ $trys > 3 ]]; then fatalError "Too many checksums fails !!! Exiting"; fi
+		if [[ $trys > 3 ]]; then error "Too many checksums fails! Exiting"; fi
 
 		echo "Redownloading ...";
 		download "$@";
@@ -66,39 +71,27 @@ function downloadMulti() {
 	local packages=($(lynx -dump -listonly -dont-wrap-pre $kernelURL | grep "$1" | grep "$2" | grep "$3" | awk '{print $2}' | sort | uniq));
 
 	if [[ ${#packages[@]} < 1 ]]; then
-		fatalError "Kernel package missing. Please wait until next release";
-	fi;
+		error "Kernel package missing. Please wait until next release";
+	fi
 
 	for package in "${packages[@]}"
 	do
-		download $package
+		download $package;
 	done
-}
-
-function notifyUpdate() {
-	if [[ -x "$(command -v notify-send)" ]]; then
-		user=$(w -h | awk '{print $1}' | head -n 1)
-		userId=$(id -u $user)
-		export DISPLAY=:0.0
-		export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$userId/bus
-		su $user -c "notify-send 'Kernel Updated to $1' 'System restart required'"
-	fi
-
-	touch /tmp/ukupgrade.nr
 }
 
 function checkSameVersion() {
 	local locVersion=$(dpkg -l |grep "linux-image" | grep "$kernelmode" | awk '{print $3}' | sed -e 's/-/./' | cut -d'.' -f-4 | sed -e 's/.0.*rc/-rc/' | cut -d'.' -f-3)
 
 	if [[ $locVersion =~ $reqVersion ]]; then
-		echo "Kernel up to date. Finishing"
+		echo "Kernel up to date. Finishing";
 		exit
 	fi
 }
 
 function waitDpkg() {
 	while execCmd "fuser /var/lib/dpkg/lock"; do
-		sleep 0.5
+		sleep 0.5;
 	done
 }
 
@@ -109,7 +102,7 @@ fi
 
 displayTitle "UkTools Upgrade";
 
-if ! execCmd "ping -q -w 1 -c 1 $server"; then fatalError "No network available !!! Exiting"; fi
+if ! execCmd "ping -q -w 1 -c 1 $server"; then error "No network available! Exiting"; fi
 
 if [[ "$1" = "--simple" ]]; then
 	source $splPath ;
@@ -144,7 +137,7 @@ reqVersion=$(echo $kernelURL | awk -F"/v" '{print $2}' | cut -d'/' -f 1)
 
 checkSameVersion
 
-if ! execCmd "sudo echo 0"; then fatalError "Permission denied. Require sudo access"; fi
+if ! execCmd "sudo echo 0"; then error "Permission denied. Require sudo access"; fi
 
 checksums="$(wget -qO- $kernelURL/CHECKSUMS)"
 
@@ -160,11 +153,15 @@ waitDpkg
 
 displaySubTitle "Installing Linux Kernel $reqVersion";
 
-if ! execCmd "sudo dpkg -i /tmp/linux-*.deb" 1; then fatalError "Installation failed !!! Exiting"; fi
+if ! execCmdAndSoreErr "sudo dpkg -i /tmp/linux-*.deb"; then
+	notify "Kernel upgrade failed" "Please consult $comlog for details" "-u critical";
+	error "Kernel upgrade failed! Please consult $comlog for details";
+fi
 
 cleanTmp
 
-notifyUpdate $reqVersion
+notify "Kernel Updated to $reqVersion" "System restart required";
+touch /tmp/ukupgrade.nr;
 
 echo
 displaySubTitle "Upgrade Finished";
@@ -174,10 +171,9 @@ if [[ $arm = 1 ]]; then ./ukpurge ; fi
 if [[ $cron = 0 ]]; then
 	read -p "Do you want to reboot system now? (y/n)(10s to No):" -n 1 -t 10 -s rs
 	case "$rs" in
-		y | Y)
-			echo "Yes, reboot this now!"
-			sleep 2
-			sudo reboot ;;
-		*) echo "No, stay this wake uped!" ;;
+		y | Y)  echo "Rebooting";
+				sleep 2;
+				sudo reboot ;;
+		*)      echo "You have to reboot for using new kernel";
 	esac ;
 fi
